version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: mi_basedatos
    ports:
      - "5432:5432"
    networks:
      - mi-red
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build: ./springboot-app
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mi_basedatos
      SPRING_DATASOURCE_USERNAME: miusuario
      SPRING_DATASOURCE_PASSWORD: mipassword
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - mi-red

  angular-app:
    build: ./angular-app
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - springboot-app
    networks:
      - mi-red

volumes:
  postgres_data:

networks:
  mi-red:
